global:
  smtp_smarthost: "blackbox.zonelibre.live:25"
  smtp_from: "monitoring@terre-du-mileu.org"
  smtp_require_tls: false
  resolve_timeout: 5m

route:
  receiver: default
  group_by: ["alertname", "host"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
    - matchers:
        - alertname="Dock01_LVM_Locked_At_Boot"
      receiver: dock01-mail
      repeat_interval: 30m

receivers:
  - name: default
    email_configs:
      - to: "geekdesbois@zonelibre.live"
        send_resolved: true
        headers:
          Subject: "[Monitoring] {{ .CommonLabels.alertname }}"

  - name: dock01-mail
    email_configs:
      - to: "geekdesbois@zonelibre.live"
        send_resolved: true
        headers:
          Subject: "[CRITIQUE] DOCK01 â€“ unlock LVM requis"
