services:
  obsidian-caldav-sync:
    image: ghcr.io/geekdesbois/obsidian-caldav-sync:latest
    container_name: obsidian-caldav-sync

    restart: unless-stopped

    env_file:
      - /etc/portainer-env/obsidian-caldav.env

    volumes:
      - ${VAULT_HOST_PATH}:${VAULT_PATH}:ro

    environment:
      TZ: Europe/Paris

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    labels:
      - diun.enable=true
